server:
  port: 13080
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    spring-security-oauth-resource:
      path: /spring-security-oauth-resource/**
      url: http://localhost:13082/spring-security-oauth-resource
    oauth:
      path: /oauth/**
      url: http://localhost:13081/spring-security-oauth-server/oauth

security:
  oauth2:
    resource:
      jwt:
        key-value: 123
